---
- name: Install service files
  template:
    src: pulp-worker@.service.j2
    dest: /lib/systemd/system/pulp-worker@.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd and restart pulp workers
  become: true

- name: Set states of pulp workers
  systemd:
    daemon_reload: true
    name: pulp-worker@{{ item }}.service
    state: started
    enabled: enabled
  loop: "{{ range(0, pulp_worker_count)|list }}"
  become: true
