---
- name: Install gunicorn
  pip:
    name: gunicorn
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  become: true
  become_user: '{{ pulp_user }}'
  when: pulp_install_dir != False

- block:

    - name: Install pulp-wsgi service files
      template:
        src: pulp-wsgi.service.j2
        dest: /etc/systemd/system/pulp-wsgi.service
        owner: root
        group: root
        mode: 0644
      become: true
      notify: Restart pulp-wsgi.service

    - name: Start pulp-wsgi.service
      systemd:
        name: pulp-wsgi.service
        state: '{{ pulp_wsgi_state }}'
        enabled: '{{ pulp_wsgi_enabled }}'
        daemon_reload: true
      become: true

  when: pulp_install_wsgi_service
